title: Ceara Byrne
description: Data-Driven Design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cearabyrne.com" # Replace with your GitHub Pages URL
markdown: kramdown
theme: jekyll-theme-minimal
# Additional configuration options can be added here.

collections:
  portfolio:
    output: true
  domains:
    output: true

exclude: ["CNAME", "README.md", "Gemfile"]
