title: My Jekyll Site
description: A blog created with Jekyll for GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL
markdown: kramdown
theme: jekyll-theme-minimal
# Additional configuration options can be added here.
